/* =====================================================================
   PLAN, EXAMS AND WEIGHTS — ARE Study System
   ===================================================================== */
window.ARE = window.ARE || {};

/* Exam sittings — drive the countdowns and readiness on the Today page.
   date is YYYY-MM-DD. Change a date here if you reschedule. */
ARE.exams = [
 {d:'PA',  name:'Programming & Analysis',              date:'2026-10-22', items:75},
 {d:'PPD', name:'Project Planning & Design',           date:'2026-11-24', items:100},
 {d:'PDD', name:'Project Development & Documentation', date:'2026-12-22', items:100}
];

/* Section weights shown on the Overview page:
   [section name, low %, high %, 1 = highlight as the heaviest] */
ARE.weights = {
 pa:[['Building Analysis & Programming',37,43,1],['Site Analysis & Programming',21,27,0],['Codes & Regulations',16,22,0],['Environmental & Contextual Conditions',14,21,0]],
 ppd:[['Project Integration of Program & Systems',32,38,1],['Building Systems, Materials & Assemblies',19,25,0],['Codes & Regulations',16,22,0],['Environmental Conditions & Context',10,16,0],['Project Costs & Budgeting',8,14,0]],
 pdd:[['Construction Documentation',32,38,1],['Integration of Building Materials & Systems',31,37,1],['Project Manual & Specifications',12,18,0],['Codes & Regulations',8,14,0],['Construction Cost Estimates',2,8,0]]
};

/* Shown at the top of the Study plan page (HTML allowed). */
ARE.planNote = '<p>Front-loaded on the heaviest sections. PA gets four weeks because it is the smallest exam; PPD gets five because it has the lowest pass rate and the most calculation; PDD gets four. Three full-length timed practice exams are scheduled, one before each sitting.</p><p>Each division ends with a <strong>full-length timed practice exam on the Saturday before the sitting</strong> — a pacing rehearsal, because time management is what fails prepared candidates.</p><p><strong>The risk:</strong> the retake wait is 60 days. A failed PA on 22 October cannot be retaken until 21 December, which lands on top of PDD prep. If PA goes badly, sit PDD as planned and retake PA in January rather than trying to do both in December.</p>';

/* The weekly plan. One week per entry:
     {w:1, from:'2026-09-22', to:'2026-09-27', d:'22–27 Sep', g:'Goal for the week',
      exam:'PA exam — Thursday 22 October',   (optional)
      t:['Task one', 'Task two', ...]},
   from/to decide which week is "this week". Checkbox progress is saved per
   week number and task position, so reordering tasks inside a week moves
   their ticks with the position. Tasks starting SATURDAY/TUESDAY/THURSDAY
   are shown in red as exam-day tasks. */
ARE.plan = [
{w:1,from:'2026-09-22',to:'2026-09-27',d:'22–27 Sep',g:'Orient to the rubric, then start PA\'s heaviest section.',t:['Read the Overview and Objective map pages end to end. Write down which three sections carry the most items.','Read the PA page, section 4 only — Building Analysis & Programming. It is 28–32 of 75 items.','Drill the PA · Programming method deck until every card is rated Good.','Work the net-to-gross worked example on the PA page, then invent three of your own with different building types.','Read Problem Seeking chapters on the five steps and four considerations in your folder.','Verification: re-derive the efficiency table from memory and check it against the PA page.']},
{w:2,from:'2026-09-28',to:'2026-10-04',d:'28 Sep–4 Oct',g:'Finish PA section 4; start site analysis.',t:['Learn the 24 programmatic concepts as a list. Write them out twice from memory.','Read the PA page, section 3 — Site Analysis & Programming.','Drill the PA · Site & zoning deck.','Work the buildable-area example on the PA page with a different set of setbacks.','Read the Site Planning and Design Handbook chapters on grading and circulation.','Verification: do 15 PA practice items on this site. Any objective you miss, reread that section.']},
{w:3,from:'2026-10-05',to:'2026-10-11',d:'5–11 Oct',g:'PA codes and zoning — the section your folder covers worst.',t:['Read the PA page, section 2 — Codes & Regulations, including the full zoning taxonomy.','Learn the variance vs special exception distinction cold. It is the most reliably tested zoning item.','Work the FAR, coverage and height example, then redo it with a 12 ft floor-to-floor.','Read the PA page, section 1 — Environmental & Contextual Conditions. This is the lightest section; do not overinvest.','Drill all three PA decks, weakest-first.','Verification: do every PA practice item on this site and record which objectives you miss.']},
{w:4,from:'2026-10-12',to:'2026-10-18',d:'12–18 Oct',g:'Consolidate PA. Timed practice at the end of the week.',t:['Reread every red correction block on the PA page. These are the errors your own material would teach you.','Drill the Numbers page for the PA rows — FAR, efficiency, parking, grading, solar.','Work the Ballast PA practice problems from your folder. Note: they are image scans, so read them on screen.','Redrill any flashcard still rated Again or Shaky.','SATURDAY 17 OCT: full-length timed PA practice exam. 75 items in 3 hours, no interruptions. Use NCARB\'s updated practice exam.','Verification: score the practice exam by section and compare against the weights. Spend Sunday on your weakest section only.']},
{w:5,from:'2026-10-19',to:'2026-10-25',d:'19–25 Oct',g:'Sit PA. Start PPD on structures — the biggest gap in your folder.',exam:'PA exam — Thursday 22 October',t:['Mon–Wed: light review only. Numbers page, flashcards, no new material.','THURSDAY 22 OCT: sit Programming & Analysis.','Friday: rest. Do not start PPD the same day.','Read the PPD page, section 3.2 — Structural systems. Nothing in your folder covers this.','Learn the depth-to-span table. Steel beam span/20–28, girder span/12–15, the three joist series.','Verification: work the steel beam sizing example end to end without looking, including the deflection check.']},
{w:6,from:'2026-10-26',to:'2026-11-01',d:'26 Oct–1 Nov',g:'PPD structures and envelope.',t:['Drill the PPD · Structures deck until every card is Good.','Learn the four beam cases and the deflection limits. These are given on screen but you must know which to reach for.','Read the PPD page, thermal and envelope. Work the U-factor and dew-point example.','Learn the vapour control rule by climate, including why hot-humid reverses it.','Drill the PPD · Envelope & thermal deck.','Verification: build a wall assembly of your own, compute U, heat loss and the dew-point location.']},
{w:7,from:'2026-11-02',to:'2026-11-08',d:'2–8 Nov',g:'PPD systems — HVAC, plumbing, lighting, acoustics.',t:['Read the PPD page, HVAC system selection. Learn the four families and the space each demands.','Work the ventilation and duct-sizing example. Learn why ducts are sized for cooling.','Read the modern systems box — DOAS, chilled beams, VRF, radiant, displacement, ERV vs HRV. None of this is in MEEB.','Work the lumen-method and reverberation-time examples.','Drill the PPD · HVAC & plumbing and PPD · Lighting & acoustics decks.','Verification: do all PPD practice items tagged to section 3 and reread whatever you miss.']},
{w:8,from:'2026-11-09',to:'2026-11-15',d:'9–15 Nov',g:'PPD codes applied — the calculations, not the concepts.',t:['Read the PPD page, section 2 — Codes & Regulations, in full.','Memorise the occupant load factors. Note that business areas are 150 SF gross, not 100.','Work the occupant-load-to-egress-width example, then the exit separation example.','Learn the sprinkler thresholds as a pattern: 12,000/24,000/3 storeys, with A-2, E, H and R as the exceptions.','Drill the PPD · Codes applied and Accessibility decks.','Verification: pull IBC Tables 602, 705.8 and 716.1(2) from a code source and write them onto your own copy of the Numbers page. These are the three I could not verify.']},
{w:9,from:'2026-11-16',to:'2026-11-22',d:'16–22 Nov',g:'PPD integration — the 32–38% section. Timed practice at the end.',t:['Read the PPD page, section 4 — Project Integration. Work the floor-to-floor example twice with different parameters.','Learn the order of operations for an integration item: code envelope, zoning envelope, structural grid, floor-to-floor, core and egress, programme, cost.','Read section 5 — costs. Learn the AACE classes and the Cost of the Work definition. Do not overinvest; it is 8–14%.','Reread every red correction block on the PPD page.','SATURDAY 21 NOV: full-length timed PPD practice exam. 100 items in 4 hours 5 minutes.','Verification: score by section. PPD has the lowest pass rate of the six divisions — if you are below target, move the exam rather than sit it unprepared.']},
{w:10,from:'2026-11-23',to:'2026-11-29',d:'23–29 Nov',g:'Sit PPD. Begin PDD on documentation.',exam:'PPD exam — Tuesday 24 November',t:['Monday: light review only. Numbers page and weakest flashcards.','TUESDAY 24 NOV: sit Project Planning & Design.','Wednesday: rest.','Read the PDD page, section 2 — Construction Documentation. It is 32–38 items.','Learn the change instruments cold: addendum, ASI, CCD, change order, RFI.','Verification: explain each change instrument out loud, including what it does to contract sum and time.']},
{w:11,from:'2026-11-30',to:'2026-12-06',d:'30 Nov–6 Dec',g:'PDD documentation standards and specifications.',t:['Learn the National CAD Standard components and the eight UDS modules.','Learn the LOD ladder, especially why 350 and not 300 is the coordination level.','Read the PDD page, section 3 — Project Manual & Specifications.','Memorise the MasterFormat 2020 division list. Use the CSI PDPG in your folder, not Olin\'s.','Learn SectionFormat\'s three parts and the source vs field quality control distinction.','Verification: write out all 50 MasterFormat divisions from memory and check them.']},
{w:12,from:'2026-12-07',to:'2026-12-13',d:'7–13 Dec',g:'PDD detailing — the other big section.',t:['Read the PDD page, section 1 — Integration of Building Materials & Systems.','Learn the five control layers and trace them through a rainscreen wall from memory.','Memorise the masonry flashing and weep dimensions. They are the most dimension-heavy topic in PDD.','Learn the concrete joint types and the spacing rule of thumb.','Drill the PDD · Detailing and PDD · Documentation decks.','Verification: sketch a masonry cavity wall base detail from memory with every dimension labelled.']},
{w:13,from:'2026-12-14',to:'2026-12-20',d:'14–20 Dec',g:'PDD codes at detail, specifications review, timed practice.',t:['Read the PDD page, section 4 — Codes at detail level. Learn F vs T ratings and the flame spread classes.','Learn fireblocking vs draftstopping, and fire vs smoke dampers.','Read section 5 — cost estimates. It is 2–8 items. One pass is enough.','Reread every red correction block on the PDD page, and the whole Source corrections deck.','SATURDAY 19 DEC: full-length timed PDD practice exam. 100 items in 4 hours 5 minutes.','Verification: score by section; spend Sunday only on the weakest.']},
{w:14,from:'2026-12-21',to:'2026-12-27',d:'21–27 Dec',g:'Sit PDD.',exam:'PDD exam — Tuesday 22 December',t:['Monday: Numbers page twice through. Weakest flashcards only. No new material.','TUESDAY 22 DEC: sit Project Development & Documentation.','If any division did not pass, note that the retake wait is 60 days and book immediately — the score report\'s section breakdown is the most useful diagnostic you will get.','Write down, while it is fresh, which item types and topics felt hardest. That note is worth more than any review book for a retake.']},
];
